services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file: /media/docker_volumes/docker.env
    volumes:
      - /media/docker_volumes/radarr:/config
      - /media/libraries/movies:/movies
      - /media/usenet:/usenet
    restart: unless-stopped # Automatically restart radarr unless explicitly stopped
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:7878/radarr/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr.rule: "Host(`${DOMAIN_NAME?error}`)"
      traefik.http.routers.radarr.entrypoints: "https"
      traefik.http.routers.radarr.tls: "true"
      traefik.http.services.radarr.loadbalancer.server.port: "7878"
    networks:
      - proxy

networks:
  proxy:
    external: true
